stages:
  - test

variables:
  JAVA_VERSION: 21'
  GO_VERSION: '1.18'
  PYTHON_VERSION: '3.8'
  PHP_VERSION: '8.1'

test_go:
  stage: test
  image: golang:${GO_VERSION}-alpine
  script:
    - export CGO_ENABLED=0
    - cd qubengage-averagehours/src
    - go test -v ./...

test_java:
  stage: test
  image: gradle-jdk${JAVA_VERSION}
  script:
    - cd qubengagefailurerisk
    - chmod +x ./gradlew
    - ./gradlew test
  artifacts:
    when: always
    reports:
      junit:
        - qubengagefailurerisk/build/test-results/test/*.xml
    paths:
      - qubengagefailurerisk/build/test-results/test/


test_python:
  stage: test
  image: python:${PYTHON_VERSION}
  script:
    - cd qubengage-totalhours
    - pip install -r requirements.txt  
    - python -m unittest discover -s src

test_php_maxmin:
  stage: test
  image: php:${PHP_VERSION}-cli
  cache:
    paths:
      - qubengage-maxmin/vendor/
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq git
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  script:
    - cd qubengage-maxmin
    - composer install
    - composer dump-autoload
    - chmod +x ./vendor/bin/phpunit
    - ./vendor/bin/phpunit tests

test_php_sort:
  stage: test
  image: php:${PHP_VERSION}-cli
  cache:
    paths:
      - qubengage-sort/vendor/
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq git
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  script:
    - cd qubengage-sort
    - composer install
    - composer dump-autoload
    - chmod +x ./vendor/bin/phpunit
    - ./vendor/bin/phpunit tests

test_javascript:
  stage: test
  image: node:latest
  script:
    - cd qubengage-engagementscore
    - npm install
    - npm test
